version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: ogc-nice-postgres
    restart: always
    environment:
      POSTGRES_DB: ogc_nice
      POSTGRES_USER: ogc_user
      POSTGRES_PASSWORD: ogc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ogc-nice-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ogc_nice
      SPRING_DATASOURCE_USERNAME: ogc_user
      SPRING_DATASOURCE_PASSWORD: ogc_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
