spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ogc_nice
    username: ogc_user
    password: ogc_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev only; later we can switch to validate/none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa.open-in-view: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
